package golang

import (
	"fmt"
	"github.com/kr/pretty"
	"github.com/samlitowitz/graphqlc-gen-echo/pkg/graphqlc/echo"
	"github.com/samlitowitz/graphqlc/pkg/graphqlc"
	"go/ast"
	"go/printer"
	"go/token"
	"path"
	"strings"
)

type Generator struct {
	*echo.Generator

	config   *Config
	genFiles map[string]bool
	typeMap  map[string]*ast.Ident
}

func New() *Generator {
	g := new(Generator)
	g.Generator = echo.New()
	g.LogPrefix = "graphqlc-gen-go"
	return g
}

func (g *Generator) GenerateSchemaFiles() {}

func (g *Generator) CommandLineArguments(parameter string) {
	g.Generator.CommandLineArguments(parameter)

	for k, v := range g.Param {
		switch k {
		case "config":
			config, err := LoadConfig(v)
			if err != nil {
				g.Error(err)
			}
			g.config = config
		}
	}
	if g.config == nil {
		g.Fail("a configuration must be provided")
	}
}

func (g *Generator) GenerateAllFiles() {
	g.buildGenFilesMap()
	g.generateTypeDefinitions()
	return

	// Go type definitions
	//g.Reset()
	//g.writeFileHeader()
	//g.writeGoTypeDefinitions()
	//g.Response.File = append(g.Response.File, &graphqlc.CodeGeneratorResponse_File{
	//	Name:    g.config.Output + "types.go",
	//	Content: g.String(),
	//})

	// Go schema definition
	// Using https://github.com/graphql-go/graphql
	//g.Reset()
	//g.writeFileHeader()
	//g.writeImports([]string{"github.com/graphql-go/graphql"})
	//g.Response.File = append(g.Response.File, &graphqlc.CodeGeneratorResponse_File{
	//	Name:    g.config.Output + "schema.go",
	//	Content: g.String(),
	//})
}

func (g *Generator) generateTypeDefinitions() {
	g.buildTypeMapBase()
	for _, fd := range g.Request.GraphqlFile {
		if _, ok := g.genFiles[fd.Name]; !ok {
			continue
		}
		f := &ast.File{
			Name: ast.NewIdent(g.config.Package),
			Scope: &ast.Scope{
				Objects: make(map[string]*ast.Object),
			},
			Doc:  &ast.CommentGroup{
				List: []*ast.Comment{},
			},
			Comments: []*ast.CommentGroup{},
		}
		f.Comments = append(f.Comments, f.Doc)

		f.Doc.List = append(f.Doc.List, &ast.Comment{
			Text:  "// DO NOT MODIFY!!! This code is generated by graphqlc-gen-go.\n",
		})

		//ft := fset.AddFile(filename, -1, calculateSize(f))

		//for _, objDef := range fd.Objects {
		//	typeMap[objDef.Name] = &ast.GenDecl{
		//		Tok:    token.TYPE,
		//		Specs:  []ast.Spec{
		//			&ast.TypeSpec{
		//				Name:    nil,
		//				Assign:  0,
		//				Type:    nil,
		//				Comment: nil,
		//			},
		//		},
		//	}
		//}

		fset := token.NewFileSet()
		calculatePositions(f, fset.Base())

		err := printer.Fprint(g, fset, f)
		if err != nil {
			g.Error(err, "failed to print AST")
		}
		content := g.String()
		g.Error(fmt.Errorf("%# v\n%s\n", pretty.Formatter(f), content), "stuff")
		filename := fmt.Sprintf("%s_types.go", strings.TrimSuffix(fd.Name, path.Ext(fd.Name)))
		g.Response.File = append(g.Response.File, &graphqlc.CodeGeneratorResponse_File{
			Name:    g.config.Output + filename,
			Content: g.String(),
		})
	}
}

func calculatePositions(f *ast.File, pos int) {
	offset := pos

	// Package level comments
	for _, comment := range f.Doc.List {
		comment.Slash = token.Pos(offset)
		offset += len(comment.Text) + 2 // \n
	}

	// Package declaration and name
	f.Package = token.Pos(offset)
	offset += len("package ")
	f.Name.NamePos = token.Pos(offset)
	offset += len(f.Name.Name) + 2 // \n
}

//
//func (g *Generator) writeFileHeader() {
//	_, err := g.WriteString("// DO NOT EDIT!!!\n")
//	if err != nil {
//		g.Error(err)
//	}
//
//	_, err = g.WriteString("package " + g.config.Package + "\n")
//	if err != nil {
//		g.Error(err)
//	}
//}
//
//func (g *Generator) writeImports(packages []string) {
//	_, err := g.WriteString("import (")
//	if err != nil {
//		g.Error(err)
//	}
//	for _, pkg := range packages {
//		_, err = g.WriteString("\t\"" + pkg + "\"")
//		if err != nil {
//			g.Error(err)
//		}
//	}
//	_, err = g.WriteString(")\n")
//	if err != nil {
//		g.Error(err)
//	}
//}
//
//func (g *Generator) writeGoTypeDefinitions() {
//	if g.genFiles == nil {
//		g.buildGenFilesMap()
//	}
//
//	g.typeMap = buildBaseTypeMap()
//
//	for _, fd := range g.Request.GraphqlFile {
//		if _, ok := g.genFiles[fd.Name]; !ok {
//			continue
//		}
//
//		importPackages := make([]string, 0)
//
//		for _, scalarDef := range fd.Scalars {
//			var customType *ScalarType
//			if _, ok := g.config.ScalarMap[scalarDef.GetName()]; ok {
//				customType = &ScalarType{}
//				*customType = g.config.ScalarMap[scalarDef.GetName()]
//				importPackages = append(importPackages, customType.Package)
//			}
//			if typDef, ok := g.typeMap[scalarDef.GetName()]; !ok || typDef == nil {
//				def := &GoScalarDefinition{
//					ScalarTypeDefinitionDescriptorProto: scalarDef,
//					CustomType:                          customType,
//				}
//				g.typeMap[scalarDef.GetName()] = def
//			}
//		}
//		for _, enumDef := range fd.Enums {
//			if typDef, ok := g.typeMap[enumDef.GetName()]; !ok || typDef == nil {
//				def := &GoEnumDefinition{
//					EnumTypeDefinitionDescriptorProto: enumDef,
//				}
//				g.typeMap[enumDef.GetName()] = def
//			}
//		}
//		for _, ifaceDef := range fd.Interfaces {
//			if typDef, ok := g.typeMap[ifaceDef.GetName()]; !ok || typDef == nil {
//				def := &GoInterfaceDefinition{
//					InterfaceTypeDefinitionDescriptorProto: ifaceDef,
//				}
//				g.typeMap[ifaceDef.GetName()] = def
//			}
//		}
//		for _, iObjDef := range fd.InputObjects {
//			if typDef, ok := g.typeMap[iObjDef.GetName()]; !ok || typDef == nil {
//				def := &GoInputObjectDefinition{
//					InputObjectTypeDefinitionDescriptorProto: iObjDef,
//				}
//				g.typeMap[iObjDef.GetName()] = def
//			}
//		}
//		for _, objDef := range fd.Objects {
//			if objDef.GetName() == fd.Schema.Mutation.GetName() {
//				continue
//			}
//			if objDef.GetName() == fd.Schema.Query.GetName() {
//				continue
//			}
//			if typDef, ok := g.typeMap[objDef.GetName()]; !ok || typDef == nil {
//				def := &GoObjectDefinition{
//					ObjectTypeDefinitionDescriptorProto: objDef,
//				}
//				g.typeMap[objDef.GetName()] = def
//			}
//		}
//		for _, unionDef := range fd.Unions {
//			if typDef, ok := g.typeMap[unionDef.GetName()]; !ok || typDef == nil {
//				def := &GoUnionDefinition{
//					UnionTypeDefinitionDescriptorProto: unionDef,
//				}
//				g.typeMap[unionDef.GetName()] = def
//
//			}
//		}
//
//		for name, typDef := range g.typeMap {
//			switch def := typDef.(type) {
//			case *GoEnumDefinition:
//				g.typeMap[name] = def
//
//			case *GoInterfaceDefinition:
//				def.TypeMap = g.typeMap
//				g.typeMap[name] = def
//
//			case *GoInputObjectDefinition:
//				def.TypeMap = g.typeMap
//				g.typeMap[name] = def
//
//			case *GoObjectDefinition:
//				def.TypeMap = g.typeMap
//				g.typeMap[name] = def
//			}
//		}
//
//		g.writeImports(importPackages)
//		for _, typDef := range g.typeMap {
//			g.WriteString(typDef.Definition() + "\n")
//		}
//	}
//}

func (g *Generator) buildGenFilesMap() {
	g.genFiles = make(map[string]bool)
	for _, file := range g.Request.FileToGenerate {
		g.genFiles[file] = true
	}
}

func (g *Generator) buildTypeMapBase() {
	g.typeMap = map[string]*ast.Ident{
		"Int":     ast.NewIdent("string"),
		"Float":   ast.NewIdent("float"),
		"String":  ast.NewIdent("string"),
		"Boolean": ast.NewIdent("bool"),
		"ID":      ast.NewIdent("string"),
	}
}
